### ISSUE TITLE
Very High CPU usage after segue to a different View Controller

### ISSUE THREAD

**Issue by ugur10** [JaminZhou/StarrySky#1]
<img width="657" alt="screen shot 2017-05-24 at 10 41 39" src="https://cloud.githubusercontent.com/assets/20268759/26521433/f7ff1f36-42f0-11e7-9336-beb74f681f0a.png">

After segue to a different VC, around 45 percent of the CPU is still used by the animation closures. How can we release this?

I tried calling this destruct function...

```
func destruct(){
    layer.removeAllAnimations()
    subviews.forEach { $0.removeFromSuperview() }
}
```
...in

just before performing the segue
in the StarrySkyVC's deinit method
Still, it shows alive and hogs the CPU with 40% load. How can I destruct this? I even reset the navigation stack on the DestinationVC with...

`self.navigationController?.viewControllers = [self]`

...and I see the lines of deinit from AnimationVC, the animation delay closure is still alive.

**Comment by JaminZhou** [comment]
@ugur10 
It's my mistake, and I resolve the animation Infinite Loop.
You can see the [commit](https://github.com/JaminZhou/StarrySky/commit/7c6943ffdc64f1b0de86fbbc532501bcb97e9706)

**Comment by JaminZhou** [comment]
It's my mistake, and I resolve the animation Infinite Loop.
You can see the commit
<https://github.com/JaminZhou/StarrySky/commit/7c6943ffdc64f1b0de86fbbc532501bcb97e9706>

2017-05-27 20:28 GMT+08:00 feelnx <notifications@github.com>:

**Comment by ugur10** [comment]
When do you call the destruct function? In deinit, or prepareForSegue?

**Comment by JaminZhou** [comment]
You can call the destruct function when you want to release it immediately.
General call in deinit

**Comment by JaminZhou** [comment]
You can call the destruct function when you want to release it immediately.
General call in deinit
